name: Trigger Netlify build

on:
  push:
    branches:
      - main

jobs:
  trigger_netlify_build:
    runs-on: ubuntu-latest
    steps:
      - name: Send build hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/64402bbf2deec60067430897
