name: Push Documentation to Website

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    name: Trigger Deploy
    steps:
      -run: -X POST -d {} https://api.netlify.com/build_hooks/64402bbf2deec60067430897